#!/usr/bin/env bash
# run covid-19 files 
# git add, comit and push

dir=~/DataScience/covid-19-stats
path=/usr/local/bin

cd $dir
$path/papermill covid-19-matplotlib.ipynb ./cron/covid-19-matplotlib.ipynb 
$path/papermill covid-19-plotly.ipynb ./cron/covid-19-plotly.ipynb 
git add . 
git commit -m "update" 
git push

