#!/usr/bin/env bash
# run covid-19 files 
# git add, comit and push


papermill covid-19-matplotlib.ipynb ./cron/covid-19-matplotlib.ipynb 
papermill covid-19-plotly.ipynb ./cron/covid-19-plotly.ipynb 
papermill uk.ipynb ./cron/uk.ipynb 
git add . 
git commit -m "update" 
git push
terminal-notifier -title Covid19 -subtitle "Daily Updated" -message "Completed" -open "https://mybinder.org/v2/gh/shinokada/covid-19-stats/master"
now=$(date)
echo "launchd update completed at $now"